debian/control

refactor: remove same recommend packages

---

effects/desktopgrid/CMakeLists.txt
effects/desktopgrid/icons/add_hover.svg
effects/desktopgrid/icons/add_normal.svg
effects/desktopgrid/icons/add_press.svg
effects/desktopgrid/icons/reduce_hover.svg
effects/desktopgrid/icons/reduce_normal.svg
effects/desktopgrid/icons/reduce_press.svg
effects/desktopgrid/main.qml

feat: update the desktop grid buttons icon

---

plugins/platforms/x11/standalone/screens_xrandr.cpp

On Thankpad X230
https://github.com/linuxdeepin/internal-discussion/issues/1327

fix: screen count error when a screen removed

---

plugins/platforms/x11/standalone/glxbackend.cpp

https://github.com/linuxdeepin/internal-discussion/issues/1538
当显卡驱动存在问题时，和deepin-wm行为保持一致

Ignore depth if not found the valid GLXFBConfig

---

abstract_client.cpp
autotests/mock_effectshandler.h
client.cpp
dbusinterface.cpp
dbusinterface.h
effects.cpp
effects.h
effects/coverswitch/coverswitch.cpp
effects/desktopgrid/desktopgrid.cpp
effects/flipswitch/flipswitch.cpp
effects/presentwindows/presentwindows.cpp
libkwineffects/kwineffects.h
org.kde.KWin.xml
shell_client.cpp
tabbox/tabbox.cpp
utils.h
workspace.cpp
workspace.h

feat: support preview window

---

workspace.cpp

fix: can't visible minimized windows on preview window

---

virtualdesktops.cpp
virtualdesktops.h

https://github.com/linuxdeepin/internal-discussion/issues/1666
设置工作区数量上限为4

feat: set the virtual desktops maximum number to 4

---

client.cpp

https://github.com/linuxdeepin/internal-discussion/issues/1700
https://github.com/linuxdeepin/internal-discussion/issues/1696

fix: all the time update WM_STATE when minimized/unminimized window

---

effects/desktopgrid/main.qml

fix: fixed button icon size to 38 for desktopgrid effect

---

abstract_client.cpp
abstract_output.cpp
activation.cpp
debian/changelog
effects/multitaskview/multitaskview.cpp
effects/multitaskview/multitaskview.h
effects/presentwindows/presentwindows.cpp
input.cpp
input.h
layers.cpp
shell_client.cpp
virtualdesktops.cpp
workspace.h

set datasource object is nullptr when datasource is destroyed.

fix: set datasource object is nullptr when datasource is destroyed.

---

abstract_client.h
debian/changelog
geometry.cpp
moving_client_x11_filter.cpp
moving_client_x11_filter.h
pointer_input.cpp
pointer_input.h
shell_client.cpp
workspace.cpp
workspace.h

Topic graphics eagle 20221221

---

abstract_client.h
debian/changelog
geometry.cpp
pointer_input.cpp
pointer_input.h
shell_client.cpp
workspace.cpp
workspace.h

Topic graphics eagle 2022122

---

debian/changelog
geometry.cpp
keyboard_input.cpp

Topic graphics eagle 20221223

---

src/effects/screenshot/CMakeLists.txt
src/effects/screenshot/screenshotdbusinterface1.cpp

disable dde-dock preview notify
Log:

fix: dde-dock preview has notify

---

effects/multitaskview/multitaskview.cpp

add judge when delete workspace about window list
Log: add judge when delete workspace about window list
Bug: https://pms.uniontech.com/bug-view-179719.html

fix: add judge when delete workspace about window list

---

debian/changelog

Update version number for 5.15.11.74
Log: Update version number for 5.15.11.74
Change-Id: I2bbf93129341b96e0ed9f28d2efc8f3216ad6d1b

chore: Update version number for 5.15.11.74

---

debian/changelog

Update version number for 5.15.11.75
Log: Update version number for 5.15.11.75
Change-Id: Iee772b92036f6db30c65e4831074d55f9eaa8d44

chore: Update version number for 5.15.11.75

---

shell_client.cpp

This reverts commit b8699be307b3ce7b4babe7f04b7d4371c65c5194.

Revert "fix: splitoutline hide after window minimized"

---

debian/changelog

chore: Update version number for 5.15.11.76

chore: Update version number for 5.15.11.76

---

src/effects/multitaskview/multitaskview.cpp
src/effects/multitaskview/multitaskview.h

chore: remove dependency on dde-dock

---

CMakeLists.txt
configures/CMakeLists.txt
debian/control
debian/deepin-kwin-data.install
debian/deepin-wm-dbus.install
deepin-wm-dbus/CMakeLists.txt
deepin-wm-dbus/main.cpp
src/effects/CMakeLists.txt
src/effects/multitaskview/multitaskview.cpp

fix: remove dtkcore build dependency

---

.tx/deepin.conf
debian/changelog

chore: release 5.25.0

---

src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp

Limit the corner radius to no more than half the height.
Fix border not using window's radius.
Closed: https://github.com/linuxdeepin/developer-center/issues/3963

fix: fix rounded corner visual bug

---

src/effects/CMakeLists.txt
src/effects/black-screen/CMakeLists.txt
src/effects/black-screen/black-screen.cpp
src/effects/black-screen/black-screen.h
src/effects/black-screen/main.cpp
src/effects/black-screen/metadata.json
src/effects/black-screen/org.kde.kwin.BlackScreen.xml

Closed: https://github.com/linuxdeepin/developer-center/issues/3722

chore: add black-screen effects

---

debian/changelog

chore: release 5.25.1

---

debian/changelog

chore: release 5.24.2

---

debian/changelog

chore: release 5.25.3

---

src/effects/multitaskview/multitaskview.cpp
src/outline.h

Update dbus call to org.deepin.dde.appearance1

fix: multitaskview freeze

---

src/effects/blur/blur.cpp
src/effects/scissorwindow/scissorwindow.cpp
src/effects/scissorwindow/scissorwindow.h
src/plugins/kdecorations/deepin-chameleon/chameleon.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonshadow.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonshadow.h

- remove useless cache map
- remove force window corners radius 18
- Allows the plugin to crop on every frame update

fix dock corners

---

src/effects/multitaskview/multitaskview.cpp
src/outline.cpp
src/outline.h
src/workspace.cpp
src/workspace.h

org.deepin.dde.Appearance1 not provide the signals

fix: toggle window effect not working

---

debian/changelog

chore: release 5.25.4

---

src/effects/multitaskview/multitaskview.cpp

fix: unable to start multitasking plugin

---

debian/changelog

chore: release 5.25.5

---

data/update_default_rules.cpp
src/kcmkwin/kwintabbox/main.cpp
src/qml/tabbox/thumbnail_grid/contents/ui/main.qml

remove useless component, because plasma-framework not installed.
Issue: https://github.com/linuxdeepin/developer-center/issues/4230

fix: tabbox not working

---

src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
src/plugins/kdecorations/deepin-chameleon/deepin/dark/decoration.json

fix: wrong dark theme config

---

src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonconfig.h
src/plugins/kdecorations/deepin-chameleon/kwinutils.cpp
src/workspace.cpp

TopLevel chagned damaged arguments.
QRect -> QRegion

fix: dde-kwin-debug not working

---

debian/control

chore: remove plasma-desktop recommend

---

src/plugins/kdecorations/deepin-chameleon/chameleon.cpp
src/plugins/kdecorations/deepin-chameleon/chameleon.h

Closed: https://github.com/linuxdeepin/developer-center/issues/4771

feat: 3rd window title bar support HiDPI

---

src/effects/multitaskview/multitaskview.cpp
src/effects/multitaskview/multitaskview.qrc

Closed https://github.com/linuxdeepin/developer-center/issues/4726

Fix: not load multitasking translate

---

src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonconfig.h

Reloading configuration files is too expensive, reload configuration files only for theme changes
Closed: https://github.com/linuxdeepin/developer-center/issues/4495

fix: Title bar doesn't change with theme

---

src/workspace.cpp
src/workspace.h

Issues: https://github.com/linuxdeepin/developer-center/issues/4401

Fix: freezes when setting wallpaper

---

src/plugins/kdecorations/deepin-chameleon/chameleon.cpp
src/plugins/kdecorations/deepin-chameleon/chameleon.h
src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonconfig.h

use async call
Issue: https://github.com/linuxdeepin/developer-center/issues/4904

fix: Freeze when switching effects

---

debian/changelog

chore: release 5.25.9

---

src/plugins/kdecorations/deepin-chameleon/deepin/light/decoration.json

change the border color of window and dialog to #E0E0E0
Issue: https://github.com/linuxdeepin/developer-center/issues/4963

fix: border color of window is black

---

src/plugins/kdecorations/deepin-chameleon/chameleonshadow.cpp

Do not draw border when shadow exists.
Log: fix do not draw border when shadow exists

fix: do not draw border when shadow exists

---

src/effects/multitaskview/multitaskview.cpp

dde-appearance will call the kwin interface on the dbus interface, causing the dbus thread to be unable to respond to messages.
Issue: https://github.com/linuxdeepin/developer-center/issues/5491

fix(workspace): UI freeze

---

debian/changelog

chore: release 5.25.10

---

src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp

KWin should not activate appearance service, but QDBusInterface will activate the service by default. Do not use isValid in QDBusInterface to judge. Instead, ask dbus-daemon if the service name has owner.
Log: avoid activating appearance service

optimize: avoid activating appearance service

---

debian/changelog

chore: release 5.25.11

---

src/plugins/kdecorations/deepin-chameleon/chameleonwindowtheme.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonwindowtheme.h

https://github.com/linuxdeepin/qt5platform-plugins/pull/222
Log:

fix: stack overflow with property/setProperty

---

debian/changelog

chore: release 5.25.12

---

src/plugins/kdecorations/deepin-chameleon/chameleonwindowtheme.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonwindowtheme.h

Issue: https://github.com/linuxdeepin/developer-center/issues/6579

Revert "fix: stack overflow with property/setProperty" (#6579)

---

debian/changelog
debian/control

chore: bump version to 5.25.13

---

src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp

fix: titlebar color not change

---

src/effects/blur/blur.cpp

remove rounded function and use QPainterPath
Log:

fix: blur area

---

src/effects/scissorwindow/scissorwindow.cpp
src/plugins/kdecorations/deepin-chameleon/chameleon.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonshadow.cpp
src/plugins/kdecorations/deepin-chameleon/deepin/dark/decoration.json
src/plugins/kdecorations/deepin-chameleon/deepin/light/decoration.json

fix: border color not working

---

src/effects/blur/blur.cpp

Only when the window radius size, shape, or geometry changes, the blur area is refreshed.
Log:

chore: caching blur conditions

---

debian/changelog

chore: release 5.25.15

---

src/effects/zoom/zoom.cpp

fix: disable save zoom value

---

src/tabbox/tabboxhandler.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/4767

fix: don't elevate desktop in tabbox

---

debian/changelog

chore: reelase 5.25.17

---

configures/deepin-kwinrulesrc

log: https://github.com/linuxdeepin/developer-center/issues/5910

chore: dde-polkit-agent should alaway keep above

---

configures/deepin-kwinrulesrc

Reverts linuxdeepin/deepin-kwin#248

Revert "chore: dde-polkit-agent should alaway keep above"

---

src/splitoutline.cpp
src/splitoutline.h
src/workspace.cpp

Log: https://github.com/linuxdeepin/developer-center/issues/5932

fix: never clearSplitOutline when composite suspend

---

src/effects/multitaskview/multitaskview.cpp

Can't close workspace using gesture
Log:

fix: multitasking view

---

debian/changelog

chore: release 5.25.19

---

src/tabbox/tabbox.cpp
src/tabbox/tabboxhandler.cpp

log: use with https://github.com/linuxdeepin/deepin-kwin/pull/244

fix: don't set all clients minimized when show desktop

---

debian/changelog

chore: release 5.25.20

---

src/abstract_client.cpp
src/dbusinterface.cpp
src/workspace.cpp
src/workspace.h

QObject::setProperty not working.
Log:

fix: preview window not restore window minimized

---

debian/control

missing plasma-framework
Issue: https://github.com/linuxdeepin/developer-center/issues/5885 Log:

fix: split window not snap effect

---

configures/deepin-kwinrc
debian/changelog
debian/control

chore: release 5.25.21

---

src/scripts/ddelaunchpad/contents/main.js

only check title
Issue: https://github.com/linuxdeepin/developer-center/issues/7946 Log:

fix: launchpad has new name

---

debian/changelog

chore: release 5.25.22

---

CMakeLists.txt
debian/changelog
debian/control
src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonshadow.cpp
src/plugins/kdecorations/deepin-chameleon/deepin/dark/decoration.json
src/plugins/kdecorations/deepin-chameleon/deepin/light/decoration.json
src/plugins/kdecorations/deepin-chameleon/main.cpp
src/rulebooksettings.cpp
src/rules.cpp

choree: release 5.25.23

---

debian/changelog
src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp

fix: fix a crash when no effect

---

autotests/test_window_paint_data.cpp
src/deleted.cpp
src/deleted.h
src/effects.cpp
src/effects.h
src/effects/blur/blur.cpp
src/internal_client.cpp
src/internal_client.h
src/libkwineffects/deepin_kwineffects.h
src/tabbox/tabboxhandler.cpp
src/toplevel.h
src/unmanaged.cpp
src/unmanaged.h

fix: tabbox not blur background

---

src/plugins/kdecorations/deepin-chameleon/chameleon.cpp
src/plugins/kdecorations/deepin-chameleon/deepin/dark/decoration.json
src/plugins/kdecorations/deepin-chameleon/deepin/light/decoration.json
src/x11client.cpp

remove fallback icon and update pos
Issue: https://github.com/linuxdeepin/developer-center/issues/8427 Log:

chore: remove fallback icon

---

debian/changelog

log:
测试：
- https://github.com/linuxdeepin/developer-center/issues/8227

chore: release 5.25.25

---

debian/changelog
src/tabbox/tabboxhandler.cpp

This reverts commit 9b303eeb5a0b7b938419ddec02eda0777d354c2e.

release 5.25.26

---

configures/deepin-kwinrulesrc

log: update /etc/xdg/deepin-kwinrulesrc
https://github.com/linuxdeepin/developer-center/issues/9053

fix: dde-shell should show on all workspace

---

configures/deepin-kwinrc

log: https://github.com/linuxdeepin/deepin-kwin/pull/261

chore: set 4 workspace count

---

src/effects/multitaskview/multitaskview.cpp
src/effects/splitscreen/splitprevieweffect.cpp
src/effects/splitswap/splitswap.cpp
src/outline.cpp
src/windowstyle/windowstylemanager.cpp
src/workspace.cpp
src/workspace.h

log:
com.deepin.daemon.ImageBlur -> org.deepin.dde.ImageBlur1
com.deepin.daemon.Appearance -> org.deepin.dde.Appearance1

fix: imageblur and appearance dbus use v23 api

---

src/effects/multitaskview/multitaskview.cpp
src/outline.cpp

fix:  cache unblured background and fix outline

---

configures/org.kde.kwin.compositing.json

log: 默认最高特效,控制中心控制特效
https://github.com/linuxdeepin/developer-center/issues/9571

chore: default use highest effect

---

kconf_update/deepin-kwin-5.23-disable-translucency-effect.sh
src/kcms/compositing/kwincompositing_setting.kcfg
src/kcms/decoration/deepin-kwindecorationsettings.kcfg
src/kcms/desktop/deepin-virtualdesktopssettings.kcfg
src/kcms/options/kwinoptions_settings.kcfg
src/kcms/screenedges/kwinscreenedgeeffectsettings.kcfg
src/kcms/screenedges/kwinscreenedgescriptsettings.kcfg
src/kcms/screenedges/kwinscreenedgesettings.kcfg
src/kcms/screenedges/kwintouchscreenedgeeffectsettings.kcfg
src/kcms/screenedges/kwintouchscreenscriptsettings.kcfg
src/kcms/screenedges/kwintouchscreensettings.kcfg
src/kcms/tabbox/deepin-kwinpluginssettings.kcfg
src/kcms/tabbox/deepin-kwinswitcheffectsettings.kcfg
src/kcms/tabbox/deepin-kwintabboxsettings.kcfg
src/kcms/virtualkeyboard/deepin-virtualkeyboardsettings.kcfg
src/kcms/xwayland/kwinxwaylandsettings.kcfg
src/virtualdesktops.cpp

chore: copy all old data of VirtualDesktops

---

.reuse/dep5
LICENSES/BSD-3-Clause.txt
LICENSES/CC-BY-4.0.txt
LICENSES/GPL-2.0-only.txt
LICENSES/GPL-2.0-or-later.txt
LICENSES/GPL-3.0-only.txt
LICENSES/GPL-3.0-or-later.txt
LICENSES/LGPL-2.0-only.txt
LICENSES/LGPL-2.0-or-later.txt
LICENSES/LGPL-2.1-only.txt
LICENSES/LGPL-2.1-or-later.txt
LICENSES/LGPL-3.0-only.txt
LICENSES/MIT.txt
README.zh_CN.md
debian/changelog
debian/control

chore: release 5.27.2.202

---

debian/control

https://github.com/linuxdeepin/developer-center/issues/9740

fix: not show tabbox

---

debian/changelog

chore: release 5.27.2.203

---

configures/deepin-kwinrulesrc
debian/changelog
src/effects/fullscreen/package/metadata.json
src/effects/maximizeex/maximizeeffect.cpp
src/effects/maximizeex/maximizeeffect.h
src/effects/multitaskview/multitaskview.cpp
src/effects/multitaskview/multitaskview.h
src/effects/splitscreen/qml/main.qml
src/effects/splitscreen/splitprevieweffect.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonconfig.h
src/plugins/kdecorations/deepin-chameleon/deepin/dark/decoration.json
src/scene/surfaceitem.cpp
src/scripting/workspace_wrapper.cpp
src/scripting/workspace_wrapper.h
src/scripts/ddelaunchpad/contents/main.js
src/scripts/minimizeall/contents/code/main.js
src/window.cpp
src/window.h
src/windowstyle/windowradius.cpp
src/windowstyle/windowshadow.cpp
src/windowstyle/windowstylemanager.cpp
src/workspace.cpp
src/workspace.h
src/x11window.cpp
src/x11window.h

resubmit 295

---

src/input.cpp

touch event active and raise window
Log: touch event active and raise window
Bug: https://pms.uniontech.com/bug-view-273835.html

fix: touch event active and raise window

---

src/useractions.cpp
src/workspace.h

add shortcut key registration
Log: add shortcut key registration
Bug: https://pms.uniontech.com/bug-view-270341.html

fix: add shortcut key registration

---

src/placement.cpp

cascade placement
Log: cascade placement
Bug: https://pms.uniontech.com/bug-view-217473.html
Bug: https://pms.uniontech.com/bug-view-275015.html
Change-Id: I9ea7d15bd4d57ef365a3dd3cbf51ba4b1ca13a11

fix: cascade placement

---

debian/changelog

release 5.27.2.210
Log: release 5.27.2.210

chore: release 5.27.2.210

---

src/useractions.cpp
src/virtualdesktops.cpp

unite kglobalaccel fix this
Log: unite kglobalaccel fix this
Bug: https://pms.uniontech.com/bug-view-276461.html
Bug: https://pms.uniontech.com/bug-view-273815.html

fix: fix issue about shortcut force cover

---

src/CMakeLists.txt
src/composite.cpp
src/dbusinterface.cpp
src/dbusinterface.h
src/debugpixmap.cpp
src/debugpixmap.h
src/org.deepin.KWin.xml
src/scene/surfaceitem_x11.cpp
src/window.cpp
src/workspace.cpp
src/workspace.h

add interface to save debug pixmap of window
Log: add interface to save debug pixmap of window
Change-Id: If81035114cd62a3f86ada4b8a06b1a2f4e5b4b79

feat: add interface to save debug pixmap of window

---

src/workspace.cpp
src/workspace.h

adapter tile window signal
Log: adapter tile window signal
Bug: https://pms.uniontech.com/bug-view-276561.html

fix: adapter tile window signal

---

src/effects/multitaskview/multitaskview.cpp
src/effects/multitaskview/multitaskview.h
src/plugins/kdecorations/deepin-chameleon/chameleonconfig.h
src/workspace.h

adapter multitask view dconfig
Log: adapter multitask view dconfig
Bug: https://pms.uniontech.com/bug-view-276617.html

fix: adapter multitask view dconfig

---

src/useractions.cpp
src/virtualdesktops.cpp
src/workspace.h

revert shorcut force
Log: revert shorcut force
Bug: https://pms.uniontech.com/bug-view-276461.html
Bug: https://pms.uniontech.com/bug-view-273815.html

fix: revert shorcut force

---

debian/changelog

release 5.27.2.211
Log: release 5.27.2.211

chore: release 5.27.2.211

---

src/effects/multitaskview/multitaskview.cpp

fix issue about incomplete display of prompt language in multitask
Log: fix issue about incomplete display of prompt language in multitask
Bug: https://pms.uniontech.com/bug-view-276473.html

fix: fix issue about incomplete display of prompt language in multitask

---

debian/deepin-kwin-x11.postinst
src/effects/multitaskview/multitaskview.cpp
src/effects/multitaskview/multitaskview.h

remove super+A\W shortcut
Log: remove super+A\W shortcut
Bug: https://pms.uniontech.com/bug-view-279457.html

fix: remove super+A\W shortcut

---

src/x11window.cpp

cancel desktop transparent
Log: cancel desktop transparent
Bug: https://pms.uniontech.com/bug-view-271087.html

fix: cancel desktop transparent

---

debian/changelog

release 5.27.2.212
Log: release 5.27.2.212

chore: release 5.27.2.212

---

debian/changelog

release 5.27.2.213
Log: release 5.27.2.213

chore: release 5.27.2.213

---

src/effects/multitaskview/multitaskview.cpp
src/effects/splitscreen/splitprevieweffect.cpp
src/effects/splitswap/splitswap.cpp
src/workspace.h

adapter dde dbus
Log: adjust dbus imageblur to imageeffect
Bug: https://pms.uniontech.com/bug-view-288537.html

fix: adjust dbus imageblur to imageeffect

---

debian/changelog

release 5.27.2.214
Log: release 5.27.2.214

chore: release 5.27.2.214

---

debian/changelog
src/effects/multitaskview/multitaskview.cpp

Avoid slow interface calls that may cause kwin blocking
pms: BUG-308517

chore: change the wallpaper setting interface to asynchronous

---

debian/deepin-kwin-x11.links
debian/deepin-kwin-x11.lintian-overrides

chore: remove unused link

---

src/workspace.cpp
src/workspace.h

Log:
QuickTileWindow -> TileActiveWindowChanged
WindowMaximize -> ToggleActiveWindowMaximizeChanged

fix: com.deepin.wm dbus has changed in v25

---

debian/changelog

chore(debian): update version to 6.0.3

---

debian/changelog
debian/deepin-kwin-common.install

fix(debain): kpackage has moved to kf6

---

src/scripting/workspace_wrapper.cpp
src/scripting/workspace_wrapper.h
src/window.cpp
src/window.h

log: cherry pick https://github.com/linuxdeepin/deepin-kwin/pull/298/commits/c446ce761e1348d8088afea80ff091d397856f82

fix: force launcher size to be set to screen size

---

src/window.cpp
src/window.h
src/windowstyle/windowstylemanager.cpp
src/x11window.cpp

add judge about mouseInputAreaMargin from dtk win in isResizable
Log:
Issues: linuxdeepin/developer-center#10206
Issues: linuxdeepin/developer-center#10122
cherry-pick from https://github.com/zy-seven/deepin-kwin/commit/21a970e79a82285a148f1057013dee7bde08bd23

fix: add judge about mouseInputAreaMargin from dtk win in isResizable

---

debian/changelog

log:
fix: get an empty filteredProcessList from dbus
chore(effects): rename all effects same with uos 20

chore(debain): update version to 6.0.7

---

debian/changelog

chore(debian): update version to 6.0.8

---

po/en_GB/kwin.po

1. Added missing window control string translations
2. Included standard window management actions like Minimize, Maximize, Move, Resize
3. Added workspace-related action translations
4. Fixed the file ending by adding a newline character
chore: 更新翻译文件并添加窗口控制字符串
1. 添加了缺失的窗口控制字符串翻译
2. 包含标准窗口管理操作如最小化、最大化、移动、调整大小
3. 添加了工作区相关的操作翻译
4. 修复了文件结尾缺少换行符的问题

chore: update translation file with window control strings
