layers.cpp

Summary:
When the window is deleting, if the window is the currentClient
of the TabBox, it will try to reset the currentIndex of the TabBox.
If necessary, the TabBox will update the highlighted window,
and if the kwin compositing is closed at this time, the TabBox
will try to call the restack function. The old currentClient is
placed under the new client. This will cause the currentClient
to be destroy to be re-added to the unconstrained_stacking_order
and crash when accessing the object in the unconstrained_stacking_order
BUG: 330965
Test Plan:
Disable Compositing
Show tabbox window
Click the close button on the tabbox to close the currently highlighted window
https://github.com/linuxdeepin/internal-discussion/issues/1333

Avoid crash with on alt+tab(tabbox) view on close it current window

---

effects/desktopgrid/main.qml

修复在Qt 5.7.x 环境中Super+S工作区界面无法显示添加/删除按钮

fix: no QtQuick.Controls 2.1 in Qt 5.7.x

---

plugins/platforms/x11/standalone/screens_xrandr.cpp

On Thankpad X230
修复在X230上，拔掉外接屏幕后kwin未正确识别

fix: screen count error when a screen removed

---

plugins/kdecorations/aurorae/src/lib/themeconfig.cpp

fix: https://github.com/linuxdeepin/internal-discussion/issues/1481
If the primary screen DPI is 192(Multiple of 96).
Plasma's Svg library supports integer multiple scale,
so when the scaling ratio is an integer multiple,
the size of the "borders" and "paddings" should be set correctly.
See: cada139547705664e892af4c57676d0410aadd85
修复第一次进入桌面时，如果屏幕缩放设置为整数倍（如 2/3），则使用KWin时窗口标题栏绘制区域异常。
原因是，kwin绘制svg的控件只支持整数倍缩放，之前为了修复高分屏非整数倍缩放时标题栏的绘制错误，将对borders和paddings的缩放直接移除了，因此导致svg控件本身的缩放开启后的显示异常。

fix: the title area is wrong

---

scene_opengl.cpp

https://github.com/linuxdeepin/internal-discussion/issues/1622

fix: crash when the "width"/"height" value is 0

---

input.cpp
input.h
plugins/platforms/x11/standalone/xinputintegration.cpp
pointer_input.cpp
pointer_input.h

在xorg中，一个触摸点的touchUpdate和touchEnd事件只会发送给touchBegin事件的接收者，
也就是说，当手指已经按在触屏上后，在此之后kwin成功grab了触屏和鼠标事件，但在grab之前
已经按下的触摸点的后续事件kwin中也无法接收。这样情况发生于：一个client收到touchBegin
后请求_NET_WM_MOVERESIZE，之后手指移动时无法移动窗口，因此，此处监听原始的触屏事件，
用于处理此问题。

feat: support use touch screen move/resize window

---

client.cpp
client.h

在kwin环境中，如果窗管开启了3D模式
使用wps打开一个文档文件，在wps进程比较卡顿的情况下
很容易导致此窗口内容没有被绘制的问题

fix: the wps window can't visible

---

client.cpp
workspace.cpp
workspace.h

任何新窗口准备获取焦点时都退出显示桌面模式（除Desktop类型外）
且在退出显示桌面模式时不要将跳过任务栏类型的窗口或在进入此模
式之后创建的窗口最小化
https://github.com/linuxdeepin/internal-discussion/issues/1710

fix: always exit showing desktop mode on open windows

---

netinfo.cpp

fix client can't get input focus if current focus in child window of it
See: https://github.com/linuxdeepin/qt5dxcb-plugin/pull/14
Fix: https://github.com/linuxdeepin/internal-discussion/issues/1843
可以使用 deepin-appstore -platform xcb 命令测试

fix: call setInputFocus for actived client

---

effects.cpp
effects.h
effects/screenshot/screenshot.cpp
effects/screenshot/screenshot.h
libkwineffects/kwineffects.h
plugins/platforms/drm/remoteaccess_manager.cpp
screencast/screencastmanager.cpp
wayland_server.cpp
wayland_server.h

add prohibit screenshot.
add dde restrict check if clients whitelist show up. 
probhibited screenshot access to drm remote interface. 
prohibit screencast check conditions wrong.
this commit is cherry-pick from b989c a6226 a6b7e b373b.
Log: add prohibit screenshot
Change-Id: If6703980ab81ad21ba754effedeb9d1c1fd99226

feat: add prohibit screenshot

---

shell_client.cpp
shell_client.h

The screen had been changed, the window position is outof the
screen, should uUpdate screen lock position immediately.
Log: Update screen lock position when screen has been changed
Bug: https://pms.uniontech.com/bug-view-163333.html
Signed-off-by: Chaojiang Luo <luochaojiang@uniontech.com>

fix: Update screen lock position when screen has been changed

---

geometry.cpp
placement.cpp
shell_client.cpp
workspace.cpp

cancel splitoutline before touchpad splitscreen
Log: cancel splitoutline before touchpad splitscreen
Bug: https://pms.uniontech.com/bug-view-175305.html
Change-Id: I997714c9c3c1f7e6b8fc3cd762a251be39409e87

fix: splitoutline apper after touchpad splitscreen

---

src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp

Revert "fix: the problem of dtk setting window theme radius conflict"
This reverts commit 8d9a526680c604c21e0d2add769f7d02165526f8.

fix: bypass window not use window radius

---

configures/CMakeLists.txt
debian/deepin-kwin-data.install

KConfig::openConfig will search files in GenericConfigLocation

fix: not install config files into GenericConfigLocation

---

src/input.cpp

Don't use the RecordEventMonitor in wayland mode.

Fix crash on exit in wayland

---

configures/deepin-kwinrc

dde-launcher dbus service not working.

fix: cannot use super to launch dde-launcher on wayland mode

---

src/windowitem.cpp

For the no decoration windows, we can using _KDE_NET_WM_SHADOW to render shadows for it, the shadow item needs after stack of the window to avoid mask window.

fix: ensure the shadow item after stack of the window

---

src/plugins/kdecorations/deepin-chameleon/chameleon.cpp
src/plugins/kdecorations/deepin-chameleon/chameleon.h
src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonshadow.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonshadow.h

If no specific value is obtained from the window,
the default theme configuration will fall back to use, but the default theme configuration is a pointer,
which causes all windows to share the same configuration.

fix: All windows share a theme

---

debian/control
src/backends/x11/standalone/CMakeLists.txt
src/backends/x11/standalone/glxbackend.cpp
src/backends/x11/standalone/glxbackend.h

The GLX_EXT_buffer_age allow extension is to expose enough information to applications about how the driver manages the set of front and back buffers associated with a given surface to allow applications to re-use the contents of old frames and minimize how much must be redrawn for the next frame.
If using GLX_EXT_buffer_age on kwin, it's using the repaint area from the damage areas to do partial refresh in compositor. when dpms off and dpms on soon(The interval of one second may be repeated), you will see the screen is flash with the some part of black in some frame, maybe one buffer of front buffer and back buffer is broke, and kwin only draw a part of the buffer, so the other part of the buffer is black.
Upstream bug: https://gitlab.freedesktop.org/xorg/xserver/-/issues/1296
Issue: …

fix: DPMS off seems to blank compositor's back or front buffer

---

src/effects/scissorwindow/scissorwindow.cpp

dde-dock loses rounded corners when using minimized window animation
Closed: https://github.com/linuxdeepin/developer-center/issues/4258

chore: allow window cropping on screen update

---

src/effects/blur/blur.cpp
src/effects/scissorwindow/scissorwindow.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonshadow.cpp

Get the minimum available rounded corners on x and y, and calculate the smallest available again, which can make the rounded corners appear rectangular.
Closed: https://github.com/linuxdeepin/developer-center/issues/4223

chore: Pick the best fillet

---

src/plugins/kdecorations/deepin-chameleon/chameleontheme.cpp
src/plugins/kdecorations/deepin-chameleon/deepin/dark/decoration.json

当通过修改~/.local/share/deepin/themes/deepin/dark/decoration.json和~/.local/share/deepin/themes/deepin/light/decoration.json来自定义第三方应用标题栏高度时，会出现操作按钮消失的情况，应用本修复后则可以正常生效；另外修复了深色模式下对话框标题文字颜色为黑色看不清的问题：https://github.com/linuxdeepin/developer-center/issues/5133

fix: button disappeared when using custom config; dialog title font color in dark mode

---

src/plugins/kdecorations/deepin-chameleon/chameleon.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
src/workspace.cpp

because appearance has a fake wm interface, it will take a loog time to init, so need to check when appearance interface is ok, then read the property

fix: freeze because of appearance

---

src/abstract_client.cpp

fix: After using the text tube to split the screen, click the maximize button, the right angle of the window edge becomes a rounded corner
This modification will only perform the unsplit operation when both conditions are met (the window cannot be minimized and cannot be maximized) to ensure the consistency of the split state.
Issue: https://github.com/linuxdeepin/developer-center/issues/4956

fix: click the maximize button, the right angle of the window edge becomes rounded

---

src/plugins/kdecorations/deepin-chameleon/chameleon.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonconfig.h

Due to start order, kwin cannot get xsettings set by startdde from root window. Just use dbus to fetch global window radius info.
Log: fix incorrect window radius of 3rdparty window

fix: incorrect window radius of 3rdparty window

---

src/splitoutline.cpp

When there is no active window, splitoutline should not respond to mousePressEvent.
Log: fix crash when there is no active window

fix: crash when there is no active window

---

src/plugins/kdecorations/deepin-chameleon/chameleonsplitmenu.cpp
src/plugins/kdecorations/deepin-chameleon/deepin/light/icons/four_split_frame.svg
src/plugins/kdecorations/deepin-chameleon/deepin/light/icons/two_split_frame.svg

Radius of split menu does sync with window radius. Just let window manager decide the window radius.
Log: fix incorrect radius of split menu

fix: incorrect radius of split menu

---

src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonconfig.h

ChameleonConfig::init may be invoked after appearance interface is ready, therefore cannot receive ownerChanged signal. Just try once in init and then connect to watcher.
Log: fix missing owner changed signal

fix: missing owner changed signal

---

src/splitmanage.cpp

SplitManage::isShowSplitLine is called in SceneOpenGL::paintCursor.
too many unnecessary logs...

chore: remove unnecessary logs

---

src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonconfig.h

DBus connection to appearance interface must exist until config destroyed. Change local variable to member smart pointer.
Log: fix wrong life span of appearance connection

fix: wrong life span of appearance connection

---

src/useractions.cpp

Log: when unset font in QSS, it works
https://github.com/linuxdeepin/developer-center/issues/6119
https://github.com/linuxdeepin/developer-center/issues/4932

fix: user actions menu's font not follow system

---

src/effects/multitaskview/multitaskview.cpp

Log: https://github.com/linuxdeepin/developer-center/issues/7149

fix: don't block gui when get workspace background

---

src/rootinfo_filter.cpp

Log: _GTK_SHOW_WINDOW_MENU 和 _GTK_FRAME_EXTENTS 已经在 kwindowsystem 中设置了

chore: remove outdate xcb property setting for gtk

---

src/effects/multitaskview/multitaskview.cpp
src/effects/multitaskview/multitaskview.h

log: dde-appearance 壁纸相关设置的部分接口需要通过 dbus 调用 kwin
接口导致卡钝，之前使用 QDBus::BlockWithGui 避免，但是引入其他问题
在 multitaskview 保存一份数据避免调用 dbus

fix: cache background file list in kwin

---

debian/changelog
src/plugins/kdecorations/deepin-chameleon/chameleon.cpp

setBorders 触发 updateShape 时如果 dde-launchpad 没有来得及设置边框，可能会析构 Chameleon

 fix: segmentation fault when stop compositing && 5.25.27-kwin.5.24.3

---

src/window.cpp
src/workspace.cpp

wrong __deepin_kwin_minimized property tag.
Log: hoverleave dde-dock preview,window show error
Issue: https://github.com/linuxdeepin/developer-center/issues/9488

fix: hoverleave dde-dock preview,window show error

---

src/effects/screenshot/screenshotdbusinterface2.cpp

log: 当所有应用都最小化或者隐藏时，如果触发dock预览需要 kwin 提供对应 windows 截图 这一工作在ScreenShotEffect::paintScreen完成，如果桌面没有显示任何窗口，并且dock 被dbus block gui,那么 renderloop 就不会触发 paintScreen
https://github.com/linuxdeepin/developer-center/issues/9035

fix: schedule repaint after call takeScreenShot

---

kconf_update/deepin-kwin.upd
kconf_update/deepin-kwinrules-5.23-virtual-desktop-ids.py
src/config-kwin.h.cmake

fix: missing rename for deepin-kwinrc

---

src/x11window.cpp

使用 ClassHint 和 XApp 补全缺失大小的图标
Issues: linuxdeepin/developer-center#4103

fix(TabBox): some application icons are blurry

---

src/window.cpp

cancel trigger splitswap when click browser
Log: cancel trigger splitswap when click browser
Bug: https://pms.uniontech.com/bug-view-271909.html

fix: cancel trigger splitswap when click browser

---

src/workspace.cpp

the function of maxi/restor invalid on touchpad with three fingers
Log: the function of maxi/restor invalid on touchpad with three fingers
Bug: https://pms.uniontech.com/bug-view-273125.html

fix: the function of maxi/restor invalid on touchpad with three fingers

---

debian/deepin-kwin-x11.postinst

install kwin deb fail when iso build
Log: install kwin deb fail when iso build

fix: install kwin deb fail when iso build

---

src/effects/multitaskview/multitaskview.cpp
src/outline.cpp
src/plugins/kdecorations/deepin-chameleon/chameleonbutton.cpp
src/windowstyle/windowstylemanager.cpp
src/workspace.cpp
src/workspace.h

optimize dbus monitor
Log: optimize dbus monitor
Bug: https://pms.uniontech.com/bug-view-291055.html

fix: optimize dbus monitor

---

src/backends/x11/standalone/x11_standalone_glx_backend.cpp
src/backends/x11/standalone/x11_standalone_glx_backend.h

If we change the backend or restart compositor the colormap will get leak, the colormap should be released by xcb_free_colormap before the window destoryed.
Bug: https://pms.uniontech.com/bug-view-264449.html
Log: Fix screen block issue
Change-Id: I20c4626d0ed288797cb40014fa76fccd016339a9

backends/x11: fix colormap leak

---

src/composite.cpp
src/effects/multitaskview/multitaskview.cpp

Don't show workspace preview when count max
Log: Don't show workspace preview when count max
Bug: https://pms.uniontech.com/bug-view-287273.html

fix: Don't show workspace preview when count max

---

src/main_x11.cpp

Log: Load DPlatformIntegration::buildNativeSettings failed when use qxcb, should perfer dxcb then qxcb

fix: dxcb may not loaded in qt6

---

src/effects/scissorwindow/scissorwindow.cpp

Log: fix check in ScissorWindow::shouldScissor
- https://pms.uniontech.com/bug-view-311647.html
- https://pms.uniontech.com/bug-view-311893.html

fix: should not show radius when fullscreen or splited

---

src/splitscreen/splitbar.cpp
src/splitscreen/splitbar.h

Log: enterEvent(QEvent *)  has changed to enterEvent(QEnterEvent *) in qt6, mark func as `override` is is really important

fix(splitbar): can't show when use qt6

---

src/window.cpp

Log: check tempFilteredProcessList's size before access

fix: access illegal memory in createTimespanDBusMessage

---

debian/changelog
src/effects/magiclamp/CMakeLists.txt

Log: kf6 use file name to find effects, not check id in metadata.json now
Use `qdbus org.kde.KWin /Effects org.kde.kwin.Effects.listOfEffects` to check

chore(effects): rename kwin4_effect_magiclamp to magiclamp

---

src/window.cpp

Log: convert dbusArguments to QList<QString> don't work on v23 somehow, use QVariantList

fix: get an empty filteredProcessList from dbus

---

CMakeLists.txt

1. Add auto-detection of Qt6 to determine BUILD_ON_V25 option
2. Move Qt Test package detection to where it's actually needed
3. Reorganize BUILD_TESTING option handling

chore: optimize CMakeLists.txt

---

README.md
README.zh_CN.md

Update README.md and README.zh_CN.md with:
- Project scope clarification (Deepin KWin based on KWin 5.27 with Qt6/KF6 support)
- Updated build requirements and modern CMake workflow
- Standardized contribution guidelines and community links
- Translated technical content while preserving original KWin mission statement
- New feature guidelines and plugin requirements alignment
- License information standardization

chore: Update README files for Deepin KWin Qt6/KF6 migration

---

src/effects/multitaskview/multitaskview.qrc
src/splitscreen/splitscreen.qrc

1. Added missing translation files for multitaskview.qrc including multiple language variants
2. Added missing translation files for splitscreen.qrc covering additional languages and regions
3. Removed duplicate entries for multitasking.qm and splitmenu.qm that were incorrectly placed at the end
4. Organized translation files alphabetically within each qrc for better maintainability
5. Improved internationalization support by including more localized message files
The changes ensure comprehensive language coverage and fix resource reference duplication issues in Qt resource collection (qrc) files for both multitaskview and splitscreen modules, improving application localization.
chore: 更新翻译文件引用
1. 为 multitaskview.qrc 添加缺失的翻译文件，包括多种语言变体
2. 为 splitscreen.qrc 添加缺失的翻译文件，覆盖更多语言和区域
3. 移除了在 …

chore: update translation file references
